/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const createFileRoute: typeof import('@tanstack/react-router')['createFileRoute']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useFieldArray: typeof import('react-hook-form')['useFieldArray']
  const useForm: typeof import('react-hook-form')['useForm']
  const useFormContext: typeof import('react-hook-form')['useFormContext']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useIsMutating: (typeof import('@tanstack/react-query'))['useIsMutating']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useMutation: (typeof import('@tanstack/react-query'))['useMutation']
  const useNavigate: typeof import('@tanstack/react-router')['useNavigate']
  const useQuery: (typeof import('@tanstack/react-query'))['useQuery']
  const useQueryClient: (typeof import('@tanstack/react-query'))['useQueryClient']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRouter: typeof import('@tanstack/react-router')['useRouter']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const zodResolver: typeof import('@hookform/resolvers/zod')['zodResolver']
}
